baseURL = 'https://example.org/'
languageCode = 'pt-BR'
title = 'Corrida'
theme = "ink-free"
copyright = "© Copyright Wand's efforts"

[markup.goldmark.renderer]
unsafe= true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[permalinks]
  posts = "/:year/:month/:title"

[params]
	subtitle = "Blog sobre o **meu** dia-a-dia na corrida."

	# Optional 64x64 avatar image.
	#avatar = "https://image.freepik.com/free-vector/young-man-head-with-beard-avatar-character_24877-36786.jpg"

	featherIconsCDN = false
	mermaidCDN = "https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.esm.min.mjs"

	# Site color - dark/light/auto
	mode = "auto"

	# Enable a table of contents:
	# Either "static"/true, "floating", "both", or "none" (default: static)
	# The floating TOC dissapears on mobile and adds 200px vertical space
	toc = "both"
	# Whether to truncate everything but H1/H2 headings if the last element in a TOC isn't visible. Enabled by default
	enableTocTrunate = true

	# Max tags
	maxTags = 7

	# Define words per minute to approximate reading time
	wpm = 250

	# Github base url
	github = "https://github.com/wandersoncferreira/diario-corrida"

	# For statistics, we can compare the total word count against a book of your choice
	statisticsEnabled = true
	referenceBookWords = 11500.0
	referenceBook = "The Metamorphosis"
	referenceAuthor = "Franz Kafka"

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Resultados de Provas"
url = "/resultados_provas"
weight = 3

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2
